language: python
python:
  - "2.6"
  - "2.7"
script: nosetests
install:
  - pip install coverage
  - pip install -r requirements.txt --use-mirrors
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
